#############################################
# AUTOSTART
#############################################

exec_always $HOME/.config/i3/scripts/import-gsettings

# polkit
exec --no-startup-id \
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# dex
exec --no-startup-id dex --autostart --environment i3

# monitor setup
exec --no-startup-id ~/.screenlayout/monitor.sh

# wallpaper
exec --no-startuo-id ~/.config/i3/scripts/set_wallpaper.sh

# power saving
exec --no-startup-id xset s 480 dpms 600 600 600

# notifications
exec --no-startup-id /usr/bin/dunst

# lock after suspend
exec --no-startup-id xss-lock -l ~/.config/i3/scripts/blur-lock
