######################################
# KEYBINDS
######################################

# terminal
bindsym $mod+Return exec --no-startup-id kitty

# kill
bindsym $mod+q kill

# exit menu
bindsym $mod+Shift+e exec --no-startup-id ~/.config/i3/scripts/powermenu

# reload/restart
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart

# rofi
bindsym $mod+d exec --no-startup-id rofi -modi drun -show drun \
-config ~/.config/rofi/rofidmenu.rasi

bindsym $mod+t exec --no-startup-id rofi -show window \
-config ~/.config/rofi/rofidmenu.rasi

# lock
bindsym $mod+l exec --no-startup-id ~/.config/i3/scripts/blur-lock

# fullscreen
bindsym $mod+f fullscreen toggle

# floating
bindsym $mod+Shift+space floating toggle

# split
bindsym $mod+h split h
bindsym $mod+v split v

# layouts
bindsym $mod+s layout stacking
bindsym $mod+g layout tabbed
bindsym $mod+e layout toggle split

# focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+b focus up
bindsym $mod+o focus right

# move
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+b move up
bindsym $mod+Shift+o move right

# workspace switch
bindsym $mod+Tab workspace next
bindsym $mod+Shift+Tab workspace prev

# screenshots
bindsym Print exec --no-startup-id scrot ~/%Y-%m-%d-%T-screenshot.png

bindsym $mod+Print exec --no-startup-id \
scrot -u ~/%Y-%m-%d-%T-screenshot.png

bindsym $mod+Shift+Print exec --no-startup-id \
scrot -s ~/%Y-%m-%d-%T-screenshot.png

######################################
# MULTIMEDIA
######################################

bindsym XF86AudioRaiseVolume exec --no-startup-id \
~/.config/i3/scripts/volume_brightness.sh volume_up

bindsym XF86AudioLowerVolume exec --no-startup-id \
~/.config/i3/scripts/volume_brightness.sh volume_down

bindsym XF86AudioMute exec --no-startup-id \
~/.config/i3/scripts/volume_brightness.sh volume_mute

bindsym XF86AudioPlay exec --no-startup-id playerctl play-pause
bindsym XF86AudioNext exec --no-startup-id playerctl next
bindsym XF86AudioPrev exec --no-startup-id playerctl previous

######################################
# BRIGHTNESS
######################################

bindsym XF86MonBrightnessUp exec --no-startup-id \
~/.config/i3/scripts/volume_brightness.sh brightness_up

bindsym XF86MonBrightnessDown exec --no-startup-id \
~/.config/i3/scripts/volume_brightness.sh brightness_down
