######################################
# COLORS
######################################

set $darkbluetrans  #08052be6
set $darkblue       #08052b
set $lightblue      #5294e2
set $urgentred      #e53935
set $white          #ffffff
set $black          #000000
set $purple         #e345ff
set $darkgrey       #383c4a
set $grey           #b0b5bd
set $mediumgrey     #8b8b8b
set $yellowbrown    #e1b700

######################################
# WINDOW COLORS
######################################

client.focused          $lightblue $darkblue $white \
$mediumgrey $mediumgrey

client.unfocused        $darkblue $darkblue $grey \
$darkgrey $darkgrey

client.focused_inactive $darkblue $darkblue $grey \
$black $black

client.urgent           $urgentred $urgentred $white \
$yellowbrown $yellowbrown

######################################
# BAR
######################################

bar {
    font pango: Noto Sans Regular 10

    status_command i3blocks -c ~/.config/i3/i3blocks.conf

    position top

    tray_padding 0

    strip_workspace_numbers yes

    colors {
        separator          $purple
        background         $black
        statusline         $white

        focused_workspace  $mediumgrey $grey $darkgrey $purple
        active_workspace   $lightblue  $mediumgrey $darkgrey $purple
        inactive_workspace $darkgrey   $darkgrey $grey $purple
        urgent_workspace   $urgentred  $urgentred $white $purple
    }
}
